# Generated by Django 2.1.2 on 2018-12-07 14:56

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('base_image', models.ImageField(blank=True, default=None, null=True, upload_to='images/base')),
                ('zone_detected_image', models.ImageField(blank=True, default=None, null=True, upload_to='images/zone_detected')),
                ('corresponding_data', jsonfield.fields.JSONField(default={})),
            ],
        ),
    ]
