# Generated by Django 2.1.2 on 2018-10-26 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='base_image',
            field=models.ImageField(default='null', upload_to=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='image',
            name='zone_detected_image',
            field=models.ImageField(default='null', upload_to=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='image',
            name='id',
            field=models.IntegerField(auto_created=True, primary_key=True, serialize=False),
        ),
    ]
