# Generated by Django 2.1.2 on 2018-10-31 10:24

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20181031_1115'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='corresponding_data',
            field=jsonfield.fields.JSONField(default='{}'),
        ),
        migrations.AlterField(
            model_name='image',
            name='base_image',
            field=models.ImageField(default='', upload_to=''),
        ),
        migrations.AlterField(
            model_name='image',
            name='zone_detected_image',
            field=models.ImageField(default='', upload_to=''),
        ),
    ]
