# Generated by Django 2.1.2 on 2018-10-31 10:28

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20181031_1124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='corresponding_data',
            field=jsonfield.fields.JSONField(default={}),
        ),
    ]
