# Generated by Django 2.1.2 on 2018-11-09 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20181031_1128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='base_image',
            field=models.ImageField(upload_to='images/base'),
        ),
        migrations.AlterField(
            model_name='image',
            name='zone_detected_image',
            field=models.ImageField(upload_to='images/zone_detected'),
        ),
    ]
