# Generated by Django 2.1.2 on 2019-04-08 02:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20190408_0343'),
    ]

    operations = [
        migrations.CreateModel(
            name='CorrespondingImages',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.ImageField(blank=True, default=None, upload_to='corresponding_images')),
                ('score', models.FloatField(default=0)),
                ('base_image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Image')),
            ],
        ),
    ]
