# Generated by Django 2.1.2 on 2019-04-08 03:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_correspondingimages'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='base_image',
            new_name='file',
        ),
    ]
